### ISSUE TITLE
Segmentation masks as target_masks

### ISSUE THREAD

**Issue by hvdrosa** [KosinskiLab/pyTME#2]
Hi Mark and Valentin,

I'm trying to run a match_template with a binary segmentation mask for the target (with the same shape/pixel size as the original tomogram), but I'm having the following error:

Am I missing some point during the process or do you have any other tips on how I can run `match_template` with these binary masks?

[hrosa@srv-mattei-01 template_matching_pytme]$ match_template.py -m L062_ts_016_15.44Apx.mrc --target_mask L062_ts_016_15.44Apx_Seg_mito-ribo-no-dilation_flipped.mrc --bandpass_band 0,0.25 --gaussian_sigma 1 --tilt_range 60,60 --tilt_step 3 --wedge_axes 0,2 --tilt_step 3 -i MitoRibo_eEF2_job261_filtsharp.mrc -a 15 --no_edge_padding --no_fourier_padding -o L062_ts_016_mask.pickle -s MCC
********************************************************************************
*                                 pyTME v0.1.6                                 *
********************************************************************************
Resampling template to [15.44 15.44 15.44]. Consider providing a template with the same sampling rate as the target.

> Target
  - Initial Shape:       (400, 512, 512)
  - Sampling Rate:       (15.44, 15.44, 15.44)
  - Final Shape:         (400, 512, 512)

> Template
  - Initial Shape:       (30, 30, 30)
  - Sampling Rate:       (15.44, 15.44, 15.44)
  - Final Shape:         (52, 52, 52)

> Template Mask
  - Inital Shape:        (30, 30, 30)
  - Sampling Rate:       (15.44, 15.44, 15.44)
  - Final Shape:         (52, 52, 52)

--------------------------------------------------------------------------------

> Template Matching Options
  - CPU Cores:             4
  - Run on GPU:            False [N=0]
  - Use Mixed Precision:   False
  - Assigned Memory [MB]:  191143.0 [out of 224874.0]
  - Temporary Directory:   /g/icem/hrosa/SP-RIBO/template_matching_pytme
  - Extend Fourier Grid:   False
  - Extend Target Edges:   False
  - Interpolation Order:   3
  - Score:                 MCC
  - Setup Function:        <function 'tme.matching_exhaustive.mcc_setup'>
  - Scoring Function:      <function 'tme.matching_exhaustive.mcc_scoring'>
  - Angular Sampling:      15.0 [1992 rotations]
  - Scramble Template:     False
  - Target Splits:         0:1, 1:1, 2:1 [N=1]

> Score Analysis Options
  - Analyzer:          <class 'tme.analyzer.MaxScoreOverRotations'>
  - score_threshold:   0.0
  - number_of_peaks:   1000
  - convolution_mode:  valid
  - use_memmap:        False

--------------------------------------------------------------------------------

Distributing 1 split on 1 job each using 4 cores.
Running Template Matching. This might take a while ...
Traceback (most recent call last):
  File "/g/easybuild/x86_64/Rocky/8/rome/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/joblib/parallel.py", line 862, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/bin/match_template.py", line 773, in <module>
    main()
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/bin/match_template.py", line 737, in main
    candidates = scan_subsets(
                 ^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/tme/matching_exhaustive.py", line 1474, in scan_subsets
    results = Parallel(n_jobs=outer_jobs)(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/joblib/parallel.py", line 873, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/tme/matching_exhaustive.py", line 1478, in <genexpr>
    matching_data=matching_data.subset_by_slice(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/tme/matching_data.py", line 223, in subset_by_slice
    ret.target_mask = self.subset_array(
                      ^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/tme/matching_data.py", line 133, in subset_array
    arr = Density.from_file(arr.data.filename, subset=arr_slice).data
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/g/easybuild/x86_64/Rocky/8/rome/software/pyTME/0.1.6-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/tme/density.py", line 200, in from_file
    if filename.endswith(".em") or filename.endswith(".em.gz"):
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by maurerv** [comment]
Hi Higor,

thank you for raising this issue.

Unfortunately, I was not able to reproduce your issue, so I can only hypothesise about the origin.  However, it does not look like this is related to your preprocessing regiment. The error arises in tme.matching_data.subset_array, specifically in the following code block:

```
 if type(arr) == Density:
            if type(arr.data) == np.memmap:
                arr = Density.from_file(arr.data.filename, subset=arr_slice).data
```

The target_mask is internally processed as Density instance, whose data attribute is a numpy memmap. A valid memmap possess a filename attribute that informs the program which file to read for template matching. In your case this filename attribute is 'None', which could indicate an invalid memmap.

The /g/ drives have been troublesome in the part when used as temp directory. Perhaps you could try to perform the same analysis using a cluster job, which uses /scratch for temporary files. Alternatively, you could try to specify the --temp_dir parameter of match_template
